name: Make package

on:
  workflow_dispatch:

jobs:
  pkgbuild:
    runs-on: ubuntu-latest
    container:
      image: archlinux:base-devel
    env:
      repo_name: custom-bgh
      repo_base_url: https://repo.bgh.io/arch
      repo_api_url : https://la.storage.bunnycdn.com/bgh-repo/arch
    steps:
      - uses: actions/checkout@v3
      - name: Sync and update container
        run: pacman --sync --sysupgrade --refresh --noconfirm
      - name: Prepare environment for build user
        run: |
          username=build_user
          sed --in-place \
            --expression='s@#BUILDDIR=.*@BUILDDIR=/tmp/makepkg@' \
            --expression='s@#PKGDEST=.*@PKGDEST=/tmp/packages@' \
            --expression='s@#SRCDEST=.*@SRCDEST=/tmp/sources@' \
            --expression='s@#PACKAGER=.*@PACKAGER="bgh <arch at bgh dot io>"@' \
            /etc/makepkg.conf
          useradd --create-home "${username}"
          echo "${username} ALL=(ALL) NOPASSWD: /usr/bin/pacman" > "/etc/sudoers.d/${username}"
      - name: Build package
        run: |
          cd pkgbuild/cloud-init
          su build_user
          echo "${{ secrets.GPG_PRIVKEY_B64 }}" | base64 --decode | gpg --batch --import
          su build_user --command "makepkg --syncdeps --noconfirm"
          gpg --detach-sign \
            --pinentry-mode loopback \
            --batch --passphrase "${{ secrets.GPG_PASSPHRASE }}" \
            --sign /tmp/packages/cloud-init-23.1.1-1-any.pkg.tar.zst
      - name: Upload to repo
        run: |
          curl --request PUT \
            --url "${{ env.repo_api_url  }}/${{ env.repo_name }}/os/x86_64/cloud-init-23.1.1-1-any.pkg.tar.zst" \
            --header "AccessKey: ${{ secrets.BUNNY_ACCESSKEY }}" \
            --header "Content-Type: application/octet-stream" \
            --data-binary "@/tmp/packages/cloud-init-23.1.1-1-any.pkg.tar.zst"
          curl --request PUT \
            --url "${{ env.repo_api_url  }}/${{ env.repo_name }}/os/x86_64/cloud-init-23.1.1-1-any.pkg.tar.zst.sig" \
            --header "AccessKey: ${{ secrets.BUNNY_ACCESSKEY }}" \
            --header "Content-Type: application/octet-stream" \
            --data-binary "@/tmp/packages/cloud-init-23.1.1-1-any.pkg.tar.zst.sig"
      - name: Update db
        run: |
          curl --fail --remote-name --silent "${{ env.repo_base_url }}/${{ env.repo_name }}/os/x86_64/${{ env.repo_name }}.db"
          curl --fail --remote-name --silent ${{ env.repo_base_url }}/${{ env.repo_name }}/os/x86_64/${{ env.repo_name }}.db.sig"
          if [ -f "${{ env.repo_name }}.db" ]; then gpg --verify "${{ env.repo_name }}.db.sig"; fi
          repo-add --sign "${{ env.repo_name }}.db.tar.gz" /tmp/packages/cloud-init-23.1.1-1-any.pkg.tar.zst
          curl --request PUT \
            --url "${{ env.repo_api_url  }}/${{ env.repo_name }}/os/x86_64/${{ env.repo_name }}.db" \
            --header "AccessKey: ${{ secrets.BUNNY_ACCESSKEY }}" \
            --header "Content-Type: application/octet-stream" \
            --data-binary "@${{ env.repo_name }}.db.tar.gz"
          curl --request PUT \
            --url "${{ env.repo_api_url  }}/${{ env.repo_name }}/os/x86_64/${{ env.repo_name }}.db.sig" \
            --header "AccessKey: ${{ secrets.BUNNY_ACCESSKEY }}" \
            --header "Content-Type: application/octet-stream" \
            --data-binary "@${{ env.repo_name }}.db.tar.gz.sig"
